<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CurriculmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('curriculums')->insert([
            [
                'title' => 'タイトル1',
                'thumbnail' => 'example1.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example1.com/',
                'always_delivery_flg' => 1,
                'grade_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル2',
                'thumbnail' => 'example1.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example2.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at	' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル4',
                'thumbnail' => 'example2.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example4.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル3',
                'thumbnail' => 'example1.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example3.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル5',
                'thumbnail' => 'example2.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example5.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル6',
                'thumbnail' => 'example2.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example6.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル7',
                'thumbnail' => 'example3.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example7.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル8',
                'thumbnail' => 'example3.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example8.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル9',
                'thumbnail' => 'example3.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example9.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル10',
                'thumbnail' => 'example4.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example10.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル11',
                'thumbnail' => 'example4.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example11.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル12',
                'thumbnail' => 'example4.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example12.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル13',
                'thumbnail' => 'example5.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example13.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル14',
                'thumbnail' => 'example5.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example14.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル15',
                'thumbnail' => 'example5.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example15.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル16',
                'thumbnail' => 'example6.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example16.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル17',
                'thumbnail' => 'example6.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example17.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル18',
                'thumbnail' => 'example7.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example18.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 7,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル19',
                'thumbnail' => 'example7.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example19.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 7,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル20',
                'thumbnail' => 'example7.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example20.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 7,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル21',
                'thumbnail' => 'example8.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example21.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 8,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル22',
                'thumbnail' => 'example8.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example22.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 8,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル23',
                'thumbnail' => 'example8.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example23.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 8,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル24',
                'thumbnail' => 'example9.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example24.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 9,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル25',
                'thumbnail' => 'example9.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example25.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 9,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル26',
                'thumbnail' => 'example9.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example26.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 9,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル27',
                'thumbnail' => 'example10.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example27.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル28',
                'thumbnail' => 'example10.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example28.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル29',
                'thumbnail' => 'example10.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example29.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル30',
                'thumbnail' => 'example11.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example30.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 11,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル31',
                'thumbnail' => 'example11.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example31.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 11,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル32',
                'thumbnail' => 'example11.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example32.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 11,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル33',
                'thumbnail' => 'example11.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example33.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 11,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル34',
                'thumbnail' => 'example12.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example34.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 12,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル35',
                'thumbnail' => 'example12.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example35.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 12,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'タイトル36',
                'thumbnail' => 'example12.png',
                'description' => '動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明動画の説明',
                'video_url' => 'https://www.example36.com/',
                'always_delivery_flg' => 0,
                'grade_id' => 12,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
